---
- name: Configure Ubuntu container
  hosts: ubuntu_container
  gather_facts: true
  become: true

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install additional packages
      apt:
        name:
          - vim
          - wget
          - git
          - tmux
        state: present

    - name: Ensure SSH directory has correct permissions
      file:
        path: /home/jackaltx/.ssh
        state: directory
        mode: "0700"
        owner: jackaltx
        group: jackaltx

    - name: Ensure authorized_keys has correct permissions
      file:
        path: /home/jackaltx/.ssh/authorized_keys
        state: file
        mode: "0600"
        owner: jackaltx
        group: jackaltx
