---
- name: Configure Rocky Linux container
  hosts: rocky_container
  gather_facts: no
  become: yes

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install additional packages
      dnf:
        name:
          - vim
          - wget
          - git
          - tmux
        state: present

    - name: Ensure SSH directory has correct permissions
      file:
        path: /home/jackaltx/.ssh
        state: directory
        mode: "0700"
        owner: jackaltx
        group: jackaltx

    - name: Ensure authorized_keys has correct permissions
      file:
        path: /home/jackaltx/.ssh/authorized_keys
        state: file
        mode: "0600"
        owner: jackaltx
        group: jackaltx
